services:
  frontend:
    image: jmanbre360298/pi_jmmb_front:v1
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    image: jmanbre360298/pi_jmmb_back:v1
    ports:
      - "9999:9999"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: jmanbre360298/pi_jmmb_db:v1
    environment:
      MYSQL_DATABASE: pi_bd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: