services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: pi-frontend-app:latest
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    # image: pi-backend-app:latest
    ports:
      - "9999:9999"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pi_bd
      - SPRING_DATASOURCE_USERNAME=root
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: pi_bd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: